id: I318F7B44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:17:22+00:00'
last_modified: '2022-06-08T08:02:40.294886+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9255
  title: རིན་ཆེན་གཏེར་མཛོད་མཚུར་ཕུ་པར་མའི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    E6C5:
      image_group_id: I1KG9336
      title: ''
      total_pages: 297
      order: 1
      base_file: E6C5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
